---
language: generic
os: linux
dist: xenial

addons:
  apt:
    sources:
      - avsm
    packages:
      - aspcud
      - opam

cache:
  directories:
    - $HOME/.opam

install:
  - bin/install-deps
  - eval $(opam env)

script:
  - make coveralls
