language: generic

addons:
  apt:
    sources:
      - avsm
    packages:
      - opam

cache:
  directories:
    - $HOME/.opam

install:
  - opam init -y
  - eval `opam config env`
  - opam install -y menhir oasis ppx_deriving ppx_driver 
  - (cd src && oasis setup)

script:
  - make
  - make -C src coverage

branches:
  only:
  - master

git:
  depth: 1
