---
language: generic
os: linux

jobs:
  include:
    - env: BUILD=host
      addons:
        apt:
          sources:
            - avsm
          packages:
            - aspcud
            - opam

      cache:
        directories:
          - $HOME/.opam

      install:
        - opam init -y
        - eval `opam env`
        - opam install -y menhir ppx_deriving dune

      script:
        - make
#        - make coverage

    - env: BUILD=docker
      services:
        - docker
      script:
        - docker build -t apidsl .
        - docker run --rm -v $PWD:/apidsl apidsl
#        - make tests
