---
language: generic
os: linux

addons:
  apt:
    sources:
      - avsm
    packages:
      - aspcud
      - opam

cache:
  directories:
    - $HOME/.opam

install:
  - opam init -y
  - eval `opam env`
  - opam install -y menhir ppx_deriving bisect_ppx dune

script:
  - make coveralls
