name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2

      - name: Install dependencies
        run: opam install . --deps-only --with-test
      - name: Build and run tests
        run: opam exec -- make check
      - name: Upload test coverage report to Coveralls
        run: opam exec -- bisect-ppx-report send-to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
